project:
  type: website

website:
  title: "Portfolio: Pelle Knegjes"
  page-footer: "Copyright 2024, Pelle Knegjes"
  back-to-top-navigation: true
  bread-crumbs: true
  navbar:
    background: "Green"
    left:
      - text: "Master Thesis"
        href: "Master-Thesis/MasterThesis.html"
      - text: "Geospatial Analytics and Applications"
        href: "ISSS626/ISSS626.html"
    right:      
      - href: index.qmd
        text: Home
      - about.qmd
      - icon: github
        href: https://github.com/BlumeTechnologies
        target: _blank
      - icon: linkedin
        href: https://linkedin.com/in/pelleknegjes
        target: _blank

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

