---
title: "Lesson 2: Spatial Point Patterns Analysis"
author: "Pelle Knegjes"
date: "Aug 29 2024"
date-modified: "last-modified"
execute: 
  eval: true
  echo: true
  message: false
  freeze: true
---

Spatial Point Pattern Analysis is the evaluation of the pattern, or distribution, of a set of points on a surface. It can refer to the actual spatial or temporal location of these points or also include data from point sources. It is one of the most fundamental concepts in geography and spatial analysis. This lesson aims to share with you the basic concepts and methods of Spatial Point Pattern Analysis. You will also gain hands experience on using [spatstat](https://cran.r-project.org/web/packages/spatstat/index.html), an R package specially designed for Spatial Point Pattern Analysis.

## **Content**

-   Introducing Spatial Point Patterns

    -   The basic concepts of spatial point patterns

    -   Spatial Point Patterns in real world

-   1st Order Spatial Point Patterns Analysis

    -   Kernel Density Estimation (KDE)

-   2nd Order Spatial Point Patterns Analysis

    -   Nearest Neighbour Index

    -   G-function

    -   F-function

    -   K-function

    -   L-function

## **Hands-on Exercise**

-   [Chapter 4: 1st Order Spatial Point Patterns Analysis Methods](1rst_OrderSpatialPointPatterns.html)

-   [Chapter 5: 2nd Order Spatial Point Patterns Analysis Methods](2nd_OrderSpatialPointPatterns.html)
