---
title: "In-Class Exercise 04"
author: "Pelle Knegjes"
format: html
editor: visual
date: "Aug 26 2024"
date-modified: "last-modified"
execute: 
  eval: true
  echo: true
  message: false
  freeze: true
---


```{r}
pacman::p_load(GWmodel, sf, ggstatsplot, spdep,tmap,tidyverse, knitr)
```

```{r}
hunan_sf = st_read(dsn = "data/geospatial", 
                layer = "hunan")
```

```{r}
hunan2012 = read_csv("data/aspatial/Hunan_2012.csv")
```

```{r}
hunan_sf = left_join(hunan_sf, hunan2012) %>%
  select(1:3, 7, 8, 15, 16, 31, 32)
```


```{r}
hunan_sp = hunan_sf %>%
  as_Spatial()
```


```{r}
bw_CV = bw.gwr(GDPPC ~1,
               data = hunan_sp,
               approach = "CV",
               adaptive = TRUE,
               kernel = "bisquare",
               longlat = T)

```


```{r}
bw_CVFix = bw.gwr(GDPPC ~1,
               data = hunan_sp,
               approach = "CV",
               adaptive = FALSE,
               kernel = "bisquare",
               longlat = T)


```


```{r}
gwstat = gwss(
               data = hunan_sp,
               vars = "GDPPC", 
               bw = bw_CV,
               adaptive = TRUE,
               kernel = "bisquare",
               longlat = T)


```



```{r}
gwstat_df = as.data.frame(gwstat$SDF)

```

```{r}
hunan_gstat =  cbind(hunan_sf, gwstat_df)
```


```{r}
tm_shape(hunan_gstat)+
  tm_fill("GDPPC_LM", #local mean
          n = 5,#number of classes
          style = "quantile") +
  tm_borders(alpha = 0.5) + #transparency of border
  tm_layout(main.title = "Distribution of geographically weighted mean",
            main.title.position = "center",
            main.title.size = 2.0,
            legend.text.size = 1.2,
            legend.height = 1.50,
            legend.width = 1.50,
            frame = TRUE)
  
```
